language: java
jdk:
- openjdk8
branches:
  only:
    - master
cache:
  directories:
  - "$HOME/.m2"
before_install:
- export APP_VERSION="`mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate
  -Dexpression=project.version | grep -Ev '(^\[|Download\w+:)'`-$TRAVIS_BUILD_NUMBER"
- echo $APP_VERSION
script:
- mvn versions:set -DnewVersion=$APP_VERSION
- mvn clean package
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- git commit -a -m "Set version to $APP_VERSION"
- git tag $APP_VERSION -a -m "Generated tag from TravisCI for $APP_VERSION"
- git push -q -f https://$GITHUB_API_KEY@github.com/imduffy15/keycloak-extension-playground --tags
  --tags
deploy:
  skip_cleanup: true
  provider: releases
  api_key: $GITHUB_API_KEY
  file_glob: true
  file: "**/target/*.jar"
  on:
    repo: imduffy15/keycloak-extension-playground
    tags: false
    branch: master
